language: python
python:
- '2.7'
install:
- pip install -r requirements/test.txt
script: nosetests
deploy:
  provider: pypi
  user: davydany
  password:
    secure: UD5NbnCDTsiOj3RqmxED86lSO9pC9VPCzN4T+lkM5xnuaUy8uthQ/0gi8P8J67QWyjKebar8j7DCbp0hWdvlLtfzTcKG0fie9FPSAmCLJkViDBqsup7SQXdRTihIYty76nGD0qGD4IUn0NrvZrC4/+xwVJGRiHfRKtMZcQUbqj7pOANFZgpPi58Y4JiVjKb2RNintZeSQwQeCUfK6pdU8s/+E4AJ+UL6jsXWFSLehXk7dO7NyxBsKqyNjlfQDnByelqy7Y6JyCIrOXOQKqUU/78NMXTkVxJ7OQtu7SkLLPuzc4VU8sqvDjlde6tK1xa1mGAZGELtmtxcgVKcjkUb6HCwwMAnGM1rYlRGDwaLiiLKMpciVJG0wL3jzk+sfCtJVo+0G47uODomz7wYLTUWm4F9gDVhNBVgO4WH/g+0mfXH3K9JTMV+Qdj9B9wbxZjSymamVLEwj0fofLmLRHXpJvLWrBKf+JXz3Ii6LiOc+/rLbZrvZmaWQYKjY6JnfXKnNpJE/tlu3VDwdp73BykxmBT+u3DAlZE9yXOzhFeMsZWmwG6pjplEfQPNelEVW/GdDXbhRiNUrhodg7L75SHYN/oEoEzPrFXlhii6e1YsOW9TTp7noo/abWfxRwxMSQSnsyUQVr5Rn9Gf84X03vloX+8gVLlHL0h+zp+ruT173J0=
